/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calc;
import java.util.ArrayList;

/**
 *
 * @author Aluno
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        n7 = new javax.swing.JButton();
        n8 = new javax.swing.JButton();
        n9 = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        n4 = new javax.swing.JButton();
        n5 = new javax.swing.JButton();
        n6 = new javax.swing.JButton();
        less = new javax.swing.JButton();
        n1 = new javax.swing.JButton();
        n3 = new javax.swing.JButton();
        multi = new javax.swing.JButton();
        n2 = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        div = new javax.swing.JButton();
        n0 = new javax.swing.JButton();
        area = new javax.swing.JTextField();
        equal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        n7.setFont(new java.awt.Font("Sitka Subheading", 1, 18)); // NOI18N
        n7.setText("7");
        n7.setMargin(new java.awt.Insets(25, 25, 25, 25));
        n7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n7ActionPerformed(evt);
            }
        });

        n8.setFont(new java.awt.Font("Sitka Subheading", 1, 18)); // NOI18N
        n8.setText("8");
        n8.setMargin(new java.awt.Insets(25, 25, 25, 25));
        n8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n8ActionPerformed(evt);
            }
        });

        n9.setFont(new java.awt.Font("Sitka Subheading", 1, 18)); // NOI18N
        n9.setText("9");
        n9.setMargin(new java.awt.Insets(25, 25, 25, 25));
        n9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n9ActionPerformed(evt);
            }
        });

        plus.setFont(new java.awt.Font("Sitka Subheading", 1, 18)); // NOI18N
        plus.setText("+");
        plus.setMargin(new java.awt.Insets(25, 25, 25, 25));
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });

        n4.setFont(new java.awt.Font("Sitka Subheading", 1, 18)); // NOI18N
        n4.setText("4");
        n4.setMargin(new java.awt.Insets(25, 25, 25, 25));
        n4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n4ActionPerformed(evt);
            }
        });

        n5.setFont(new java.awt.Font("Sitka Subheading", 1, 18)); // NOI18N
        n5.setText("5");
        n5.setMargin(new java.awt.Insets(25, 25, 25, 25));
        n5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n5ActionPerformed(evt);
            }
        });

        n6.setFont(new java.awt.Font("Sitka Subheading", 1, 18)); // NOI18N
        n6.setText("6");
        n6.setMargin(new java.awt.Insets(25, 25, 25, 25));
        n6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n6ActionPerformed(evt);
            }
        });

        less.setFont(new java.awt.Font("Sitka Subheading", 1, 18)); // NOI18N
        less.setText("-");
        less.setMargin(new java.awt.Insets(25, 25, 25, 25));
        less.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessActionPerformed(evt);
            }
        });

        n1.setFont(new java.awt.Font("Sitka Subheading", 1, 18)); // NOI18N
        n1.setText("1");
        n1.setMargin(new java.awt.Insets(25, 25, 25, 25));
        n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1ActionPerformed(evt);
            }
        });

        n3.setFont(new java.awt.Font("Sitka Subheading", 1, 18)); // NOI18N
        n3.setText("3");
        n3.setMargin(new java.awt.Insets(25, 25, 25, 25));
        n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n3ActionPerformed(evt);
            }
        });

        multi.setFont(new java.awt.Font("Sitka Subheading", 1, 18)); // NOI18N
        multi.setText("*");
        multi.setMargin(new java.awt.Insets(25, 25, 25, 25));
        multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiActionPerformed(evt);
            }
        });

        n2.setFont(new java.awt.Font("Sitka Subheading", 1, 18)); // NOI18N
        n2.setText("2");
        n2.setMargin(new java.awt.Insets(25, 25, 25, 25));
        n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n2ActionPerformed(evt);
            }
        });

        clear.setFont(new java.awt.Font("Sitka Subheading", 1, 18)); // NOI18N
        clear.setText("c");
        clear.setMargin(new java.awt.Insets(25, 25, 25, 25));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        div.setFont(new java.awt.Font("Sitka Subheading", 1, 18)); // NOI18N
        div.setText("/");
        div.setMargin(new java.awt.Insets(25, 25, 25, 25));
        div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divActionPerformed(evt);
            }
        });

        n0.setFont(new java.awt.Font("Sitka Subheading", 1, 18)); // NOI18N
        n0.setText("0");
        n0.setMargin(new java.awt.Insets(25, 25, 25, 25));
        n0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n0ActionPerformed(evt);
            }
        });

        equal.setFont(new java.awt.Font("Sitka Subheading", 1, 18)); // NOI18N
        equal.setText("=");
        equal.setMargin(new java.awt.Insets(25, 25, 25, 25));
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(area)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(n7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(n8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(n4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(n5))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(clear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(n1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(n2)
                                    .addComponent(n0))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(n9)
                                .addGap(18, 18, 18)
                                .addComponent(plus))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(n6)
                                .addGap(18, 18, 18)
                                .addComponent(less))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(n3)
                                .addGap(18, 18, 18)
                                .addComponent(multi))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(equal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(div)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(n8)
                        .addComponent(n9)
                        .addComponent(plus))
                    .addComponent(n7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n4)
                    .addComponent(n5)
                    .addComponent(n6)
                    .addComponent(less))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n1)
                    .addComponent(n2)
                    .addComponent(n3)
                    .addComponent(multi))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear)
                    .addComponent(div)
                    .addComponent(equal)
                    .addComponent(n0))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    String number = "";
    
    private void n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n2ActionPerformed
        // TODO add your handling code here:
        number += n2.getText();
        area.setText(number);
    }//GEN-LAST:event_n2ActionPerformed

    private void lessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessActionPerformed
        // TODO add your handling code here:
        number += less.getText();
        area.setText(number);
    }//GEN-LAST:event_lessActionPerformed

    private void multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiActionPerformed
        // TODO add your handling code here:
        
        number += multi.getText();
        area.setText(number);
    }//GEN-LAST:event_multiActionPerformed

    private void n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n3ActionPerformed
        // TODO add your handling code here:
              
        number += n3.getText();
        area.setText(number);
    }//GEN-LAST:event_n3ActionPerformed

    private void n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1ActionPerformed
        // TODO add your handling code here:
        number += n1.getText();
        area.setText(number);
    }//GEN-LAST:event_n1ActionPerformed

    private void n4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n4ActionPerformed
        // TODO add your handling code here:
        number += n4.getText();
        area.setText(number);
    }//GEN-LAST:event_n4ActionPerformed

    private void n5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n5ActionPerformed
        // TODO add your handling code here:
        number += n5.getText();
        area.setText(number);
    }//GEN-LAST:event_n5ActionPerformed

    private void n6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n6ActionPerformed
        // TODO add your handling code here:
        number += n6.getText();
        area.setText(number);
    }//GEN-LAST:event_n6ActionPerformed

    private void n7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n7ActionPerformed
        // TODO add your handling code here:
        number += n7.getText();
        area.setText(number);
    }//GEN-LAST:event_n7ActionPerformed

    private void n8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n8ActionPerformed
        // TODO add your handling code here:
        number += n8.getText();
        area.setText(number);
    }//GEN-LAST:event_n8ActionPerformed

    private void n9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n9ActionPerformed
        // TODO add your handling code here:
        number += n9.getText();
        area.setText(number);
    }//GEN-LAST:event_n9ActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        // TODO add your handling code here:
        number += plus.getText();
        area.setText(number);
    }//GEN-LAST:event_plusActionPerformed

    private void divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divActionPerformed
        // TODO add your handling code here:
        number += div.getText();
        area.setText(number);
    }//GEN-LAST:event_divActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
        // TODO add your handling code here:
         try {
            String expressao = area.getText();
            double resultado = calcularExpressao(expressao);
            area.setText(String.valueOf(resultado));
        } catch (Exception e) {
            area.setText("Erro!");
        }
    
    }//GEN-LAST:event_equalActionPerformed

    private void n0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n0ActionPerformed
        // TODO add your handling code here:
        number += n0.getText();
        area.setText(number);
    }//GEN-LAST:event_n0ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        number = "";
        area.setText(number);
    }//GEN-LAST:event_clearActionPerformed


    private double calcularExpressao(String expressao) {
        ArrayList<Double> numeros = new ArrayList<>();
        ArrayList<Character> operadores = new ArrayList<>();

        String numeroAtual = "";

        for (int i = 0; i < expressao.length(); i++) {
            char c = expressao.charAt(i);

            if (Character.isDigit(c)) {
                numeroAtual += c;
            } else if (c == '+' || c == '-' || c == '*' || c == '/') {
                numeros.add(Double.parseDouble(numeroAtual));
                operadores.add(c);
                numeroAtual = "";
            }
        }

        numeros.add(Double.parseDouble(numeroAtual));

        int i = 0;
        while (i < operadores.size()) {
            char op = operadores.get(i);

            if (op == '*' || op == '/') {
                double a = numeros.get(i);
                double b = numeros.get(i + 1);
                double parcial;

                if (op == '*') {
                    parcial = a * b;
                } else {
                    if (b == 0) {
                        throw new ArithmeticException("Divisão por zero");
                    }
                    parcial = a / b;
                }

                numeros.set(i, parcial);
                numeros.remove(i + 1);
                operadores.remove(i);
            } else {
                i++;
            }
        }

        double resultado = numeros.get(0);

        for (int j = 0; j < operadores.size(); j++) {
            char op = operadores.get(j);

            if (op == '+') {
                resultado += numeros.get(j + 1);
            } else if (op == '-') {
                resultado -= numeros.get(j + 1);
            }
        }

        return resultado;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField area;
    private javax.swing.JButton clear;
    private javax.swing.JButton div;
    private javax.swing.JButton equal;
    private javax.swing.JButton less;
    private javax.swing.JButton multi;
    private javax.swing.JButton n0;
    private javax.swing.JButton n1;
    private javax.swing.JButton n2;
    private javax.swing.JButton n3;
    private javax.swing.JButton n4;
    private javax.swing.JButton n5;
    private javax.swing.JButton n6;
    private javax.swing.JButton n7;
    private javax.swing.JButton n8;
    private javax.swing.JButton n9;
    private javax.swing.JButton plus;
    // End of variables declaration//GEN-END:variables
}
